export const FETCH_TODO = "FETCH_TODO";
export const FETCH_TODO_SUCCESS = "FETCH_TODO_SUCCESS";
export const FETCH_TODO_FAILURE = "FETCH_TODO_FAILURE";

export const SEARCH_TERM_CHANGE = "SEARCH_TERM_CHANGE";
export const SEARCH_STATE_CHANGE = "SEARCH_STATE_CHANGE";

export const MODIFY_ALARM_DAYS = "MODIFY_ALARM_DAYS";
export const DELETE_ALARM = "DELETE_ALARM";

export const CONFIGURE_NOTIFICATION = "CONFIGURE_NOTIFICATION";
export const CREATE_NOTIFICATION = "CREATE_NOTIFICATION";
export const MODIFY_NOTIFICATION = "MODIFY_NOTIFICATION";
export const DELETE_NOTIFICATION = "DELETE_NOTIFICATION";

export const SHOW_TIME_PICKER = "SHOW_TIME_PICKER";
export const SHOW_TIME_PICKER_WITH_TIME = "SHOW_TIME_PICKER_WITH_TIME";
export const ON_TIME_PICKED = "ON_TIME_PICKED";
export const HIDE_TIME_PICKER = "HIDE_TIME_PICKER";
