export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_REQUEST_SUCCESS = "LOGIN_REQUEST_SUCCESS";
export const LOGIN_REQUEST_FAILURE = "LOGIN_REQUEST_FAILURE";

export const OTP_REQUEST = "OTP_REQUEST";
export const OTP_REQUEST_SUCCESS = "OTP_REQUEST_SUCCESS";
export const OTP_REQUEST_FAILURE = "OTP_REQUEST_FAILURE";

export const RESEND_OTP_REQUEST = "OTP_REQUEST";
export const RESEND_OTP_REQUEST_SUCCESS = "RESEND_OTP_REQUEST_SUCCESS";
export const RESEND_OTP_REQUEST_FAILURE = "RESEND_OTP_REQUEST_FAILURE";

export const FETCH_TODO = "FETCH_TODO";
export const FETCH_TODO_SUCCESS = "FETCH_TODO_SUCCESS";
export const FETCH_TODO_FAILURE = "FETCH_TODO_FAILURE";

export const USER_LOGIN = "USER_LOGIN";
export const USER_LOGOUT = "USER_LOGOUT";

export const SEARCH_TERM_CHANGE = "SEARCH_TERM_CHANGE";
export const SEARCH_STATE_CHANGE = "SEARCH_STATE_CHANGE";
