export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_REQUEST_SUCCESS = "LOGIN_REQUEST_SUCCESS";
export const LOGIN_REQUEST_FAILURE = "LOGIN_REQUEST_FAILURE";

export const OTP_REQUEST = "OTP_REQUEST";
export const OTP_REQUEST_SUCCESS = "OTP_REQUEST_SUCCESS";
export const OTP_REQUEST_FAILURE = "OTP_REQUEST_FAILURE";
export const OTP_REQUEST_ERROR = "OTP_REQUEST_ERROR";

export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_REQUEST_SUCCESS = "REGISTER_REQUEST_SUCCESS";
export const REGISTER_REQUEST_FAILURE = "REGISTER_REQUEST_FAILURE";

export const RESEND_OTP_REQUEST = "OTP_REQUEST";
export const RESEND_OTP_REQUEST_SUCCESS = "RESEND_OTP_REQUEST_SUCCESS";
export const RESEND_OTP_REQUEST_FAILURE = "RESEND_OTP_REQUEST_FAILURE";

export const FETCH_TODO = "FETCH_TODO";
export const FETCH_TODO_SUCCESS = "FETCH_TODO_SUCCESS";
export const FETCH_LATER_TODO_SUCCESS = "FETCH_LATER_TODO_SUCCESS";
export const FETCH_TODO_FAILURE = "FETCH_TODO_FAILURE";

export const SEARCH_TODO = "SEARCH_TODO";
export const SEARCH_TODO_SUCCESS = "SEARCH_TODO_SUCCESS";
export const SEARCH_TODO_FAILURE = "SEARCH_TODO_FAILURE";

export const CREATE_TODO = "CREATE_TODO";
export const CREATE_TODO_SUCCESS = "CREATE_TODO_SUCCESS";
export const CREATE_TODO_FAILURE = "CREATE_TODO_FAILURE";

export const ACCEPT_TODO = "ACCEPT_TODO";
export const ACCEPT_TODO_SUCCESS = "ACCEPT_TODO_SUCCESS";
export const ACCEPT_TODO_FAILURE = "ACCEPT_TODO_FAILURE";

export const REJECT_TODO = "REJECT_TODO";
export const REJECT_TODO_SUCCESS = "REJECT_TODO_SUCCESS";
export const REJECT_TODO_FAILURE = "REJECT_TODO_FAILURE";

export const COMPLETE_TODO = "COMPLETE_TODO";
export const COMPLETE_TODO_SUCCESS = "COMPLETE_TODO_SUCCESS";
export const COMPLETE_TODO_FAILURE = "COMPLETE_TODO_FAILURE";

export const INCOMPLETE_TODO = "INCOMPLETE_TODO";
export const INCOMPLETE_TODO_SUCCESS = "INCOMPLETE_TODO_SUCCESS";
export const INCOMPLETE_TODO_FAILURE = "INCOMPLETE_TODO_FAILURE";

export const ADD_TODO = "ADD_TODO";
export const REMOVE_TODO = "REMOVE_TODO";

export const UPDATE_REMINDER_TIME = "UPDATE_REMINDER_TIME";

export const FETCH_ACTIVITIES = "FETCH_ACTIVITIES";
export const FETCH_ACTIVITIES_SUCCESS = "FETCH_ACTIVITIES_SUCCESS";
export const FETCH_ACTIVITIES_FAILURE = "FETCH_ACTIVITIES_FAILURE";

export const FETCH_TASKS_COUNT = "FETCH_TASKS_COUNT";
export const FETCH_TASKS_COUNT_SUCCESS = "FETCH_TASKS_COUNT_SUCCESS";
export const FETCH_TASKS_COUNT_FAILURE = "FETCH_TASKS_COUNT_FAILURE";

export const FETCH_NEW_TASKS = "FETCH_NEW_TASKS";
export const FETCH_NEW_TASKS_SUCCESS = "FETCH_NEW_TASKS_SUCCESS";
export const FETCH_NEW_TASKS_FAILURE = "FETCH_NEW_TASKS_FAILURE";
export const CLEAR_NEW_TASKS = "CLEAR_NEW_TASKS";

export const USER_LOGIN = "USER_LOGIN";
export const UPDATE_USER_NUMBER = "UPDATE_USER_NUMBER";
export const UPDATE_USER_DETAILS = "UPDATE_USER_DETAILS";
export const UPDATE_USER_AUTH_TOKEN = "UPDATE_USER_AUTH_TOKEN";
export const USER_LOGOUT = "USER_LOGOUT";

export const UPDATE_PROFILE = "UPDATE_PROFILE";
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
export const UPDATE_PROFILE_FAILURE = "UPDATE_PROFILE_FAILURE";

export const SEARCH_TERM_CHANGE = "SEARCH_TERM_CHANGE";
export const SEARCH_STATE_CHANGE = "SEARCH_STATE_CHANGE";

export const MODIFY_FCM = "MODIFY_FCM";
export const UPDATE_FCM_TOKEN = "UPDATE_FCM_TOKEN";
export const CREATE_LOCAL_NOTIFICATION = "CREATE_LOCAL_NOTIFICATION";
export const CREATE_FUTURE_NOTIFICATION = "CREATE_FUTURE_NOTIFICATION";
export const MODIFY_FUTURE_NOTIFICATION = "MODIFY_FUTURE_NOTIFICATION";
export const DELETE_FUTURE_NOTIFICATION = "DELETE_FUTURE_NOTIFICATION";

export const OPENED_BY_NOTIFICATION = "OPENED_BY_NOTIFICATION";
